### ISSUE TITLE
fail to build: AttributeError: 'bool' object has no attribute 'format'

### ISSUE THREAD

**Issue by come-maiz** [JaquerEspeis/webespeis#3]
La rama master tiene un error durante la ejecución de nikola build:

https://travis-ci.org/JaquerEspeis/webespeis/builds/85050185

TaskError - taskid:generate_rss:output/rss.xml

PythonAction Error

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/doit/action.py", line 383, in execute

```
returned_value = self.py_callable(*self.args, **kwargs)
```

  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/nikola/nikola.py", line 1312, in generic_rss_renderer

```
feedFormat="rss")
```

  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/nikola/utils.py", line 361, in format

```
self.values[l] = self.values[l].format(*args, **kwargs)
```

AttributeError: 'bool' object has no attribute 'format'

**Comment by come-maiz** [comment]
upstream: getnikola/nikola#2140
